site_name: NiceGUI BookList

theme:
  name: "material"
  language: ja

markdown_extensions:
  - codehilite:
      noclasses: true
      pygments_style: colorful

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
